module.exports = {
  'frampton' : { trees: null },
  'frampton-utils' : { trees: null },
  'frampton-math' : { trees: null },
  'frampton-list' : { trees: null },
  'frampton-object' : { trees: null },
  'frampton-string' : { trees: null },
  'frampton-data' : { trees: null },
  'frampton-monad' : { trees: null },
  'frampton-events' : { trees: null },
  'frampton-html' : { trees: null },
  'frampton-style' : { trees: null },
  'frampton-cache' : { trees: null },
  'frampton-signals' : { trees: null },
  'frampton-io' : { trees: null },
  'frampton-window' : { trees: null },
  'frampton-mouse' : { trees: null },
  'frampton-keyboard' : { trees: null },
  'frampton-ui' : { trees: null },
  'frampton-history' : { trees: null }
};