import Frampton from 'frampton/namespace';
import add from 'frampton-list/add';
import append from 'frampton-list/append';
import at from 'frampton-list/at';
import contains from 'frampton-list/contains';
import copy from 'frampton-list/copy';
import diff from 'frampton-list/diff';
import drop from 'frampton-list/drop';
import each from 'frampton-list/each';
import filter from 'frampton-list/filter';
import find from 'frampton-list/find';
import first from 'frampton-list/first';
import foldl from 'frampton-list/foldl';
import foldr from 'frampton-list/foldr';
import init from 'frampton-list/init';
import last from 'frampton-list/last';
import length from 'frampton-list/length';
import max from 'frampton-list/max';
import min from 'frampton-list/min';
import prepend from 'frampton-list/prepend';
import product from 'frampton-list/product';
import remove from 'frampton-list/remove';
import removeAt from 'frampton-list/remove_index';
import replace from 'frampton-list/replace';
import replaceAt from 'frampton-list/replace_index';
import reverse from 'frampton-list/reverse';
import second from 'frampton-list/second';
import split from 'frampton-list/split';
import sum from 'frampton-list/sum';
import tail from 'frampton-list/tail';
import take from 'frampton-list/take';
import third from 'frampton-list/third';
import zip from 'frampton-list/zip';

/**
 * @name List
 * @namespace
 * @memberof Frampton
 */
Frampton.List           = {};
Frampton.List.add       = add;
Frampton.List.append    = append;
Frampton.List.at        = at;
Frampton.List.contains  = contains;
Frampton.List.copy      = copy;
Frampton.List.diff      = diff;
Frampton.List.drop      = drop;
Frampton.List.each      = each;
Frampton.List.filter    = filter;
Frampton.List.find      = find;
Frampton.List.first     = first;
Frampton.List.foldl     = foldl;
Frampton.List.foldr     = foldr;
Frampton.List.init      = init;
Frampton.List.last      = last;
Frampton.List.length    = length;
Frampton.List.max       = max;
Frampton.List.min       = min;
Frampton.List.prepend   = prepend;
Frampton.List.product   = product;
Frampton.List.remove    = remove;
Frampton.List.removeAt  = removeAt;
Frampton.List.replace   = replace;
Frampton.List.replaceAt = replaceAt;
Frampton.List.reverse   = reverse;
Frampton.List.second    = second;
Frampton.List.split     = split;
Frampton.List.sum       = sum;
Frampton.List.tail      = tail;
Frampton.List.take      = take;
Frampton.List.third     = third;
Frampton.List.zip       = zip;
