import Frampton from 'frampton/namespace';
import append from 'frampton-list/append';
import contains from 'frampton-list/contains';
import copy from 'frampton-list/copy';
import diff from 'frampton-list/diff';
import drop from 'frampton-list/drop';
import each from 'frampton-list/each';
import filter from 'frampton-list/filter';
import foldl from 'frampton-list/foldl';
import foldr from 'frampton-list/foldr';
import head from 'frampton-list/head';
import init from 'frampton-list/init';
import last from 'frampton-list/last';
import length from 'frampton-list/length';
import maximum from 'frampton-list/maximum';
import minimum from 'frampton-list/minimum';
import prepend from 'frampton-list/prepend';
import product from 'frampton-list/product';
import remove from 'frampton-list/remove';
import reverse from 'frampton-list/reverse';
import split from 'frampton-list/split';
import sum from 'frampton-list/sum';
import tail from 'frampton-list/tail';
import zip from 'frampton-list/zip';

Frampton.List = {};
Frampton.List.append   = append;
Frampton.List.contains = contains;
Frampton.List.copy     = copy;
Frampton.List.diff     = diff;
Frampton.List.drop     = drop;
Frampton.List.each     = each;
Frampton.List.filter   = filter;
Frampton.List.foldl    = foldl;
Frampton.List.foldr    = foldr;
Frampton.List.head     = head;
Frampton.List.init     = init;
Frampton.List.last     = last;
Frampton.List.length   = length;
Frampton.List.maximum  = maximum;
Frampton.List.minimum  = minimum;
Frampton.List.prepend  = prepend;
Frampton.List.product  = product;
Frampton.List.remove   = remove;
Frampton.List.reverse  = reverse;
Frampton.List.split    = split;
Frampton.List.sum      = sum;
Frampton.List.tail     = tail;
Frampton.List.zip      = zip;